info:
  component: Config Server
spring:
  profiles:
    active: vault,git
  application:
    name: configserver
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        vault:
          order: 1
          scheme: http
        git:
          order: 2
          uri: https://github.com/patb23/config-repo
          basedir: /Users/shruthi/git-repo/configserver
          repos:
            - patterns: multi-repo-demo-*
              uri: https://github.com/patb23/config-repo

server:
  port: 8888
management:
  context_path: /admin
